-- AlterTable
ALTER TABLE "DreamReading" ADD COLUMN "title" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DreamReading" ADD COLUMN "note" TEXT NOT NULL DEFAULT '';
ALTER TABLE "DreamReading" ADD COLUMN "updatedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP;
